In [8]:
import numpy as np

In [9]:
# Tạo một ma trận ngẫu nhiên bậc 5
np.random.seed(0)  # Đặt seed để tái hiện kết quả
A = np.random.randint(1, 10, size=(5, 5))

# Tạo ma trận đối xứng
A = (A + A.T) // 2

print("Ma trận đối xứng bậc 5:")
print(A)

Ma trận đối xứng bậc 5:
[[6 2 5 6 8]
 [2 6 6 6 6]
 [5 6 9 5 5]
 [6 6 5 2 3]
 [8 6 5 3 4]]


In [10]:
A

array([[6, 2, 5, 6, 8],
       [2, 6, 6, 6, 6],
       [5, 6, 9, 5, 5],
       [6, 6, 5, 2, 3],
       [8, 6, 5, 3, 4]])

In [11]:
#tính trị riêng của ma trận bằng numpy
eigenvalues_np = np.linalg.eigvals(A)
print("Trị riêng của ma trận A:")
print(np.round(eigenvalues_np, 5))

Trị riêng của ma trận A:
[26.45002 -6.09195  4.8394  -0.3716   2.17414]


## Thuật toán householder

In [12]:
# lấy số bậc của ma trận 
n = A.shape[0]

# Thuật toán Householder để chuyển về dạng ba đường chéo
for i in range(n - 2):
    # Lấy vector cột cần loại bỏ phần tử
    x = A[i+1:, i]

    # Tính toán giá trị a
    a = -np.sign(x[0]) * np.linalg.norm(x)

    # Tạo vector Householder v
    v = x - a * np.eye(len(x), 1).reshape(-1)
    v = v / np.linalg.norm(v)
    v = v.reshape(-1, 1)

    # Tạo ma trận Householder H cho phần con
    H = np.eye(len(v)) - 2 * v @ v.T
    # Mở rộng H để khớp với kích thước A
    H_full = np.eye(n)
    H_full[i+1:, i+1:] = H

    # Biến đổi ma trận A
    A = H_full @ A @ H_full

# Kết quả cuối cùng
print("Ma trận ba đường chéo:")
print(np.round(A,5))


Ma trận ba đường chéo:
[[  6.      -11.35782  -0.        0.       -0.     ]
 [-11.35782  15.66667  10.13118  -0.       -0.     ]
 [ -0.       10.13118   3.45025   1.3092   -0.     ]
 [  0.        0.        1.3092   -0.04993  -0.77546]
 [ -0.       -0.       -0.       -0.77546   1.93302]]


### Kiểm tra lạị trị riêng so với ma trận ban đầu 

In [13]:
householder_enginevalues = np.linalg.eigvals(A)
print("Trị riêng của ma trận A:")
print(np.round(householder_enginevalues, 5))
print("Trị riêng của ma trận A ban đầu:")
print(np.round(eigenvalues_np, 5))

Trị riêng của ma trận A:
[26.45002 -6.09195  4.8394  -0.3716   2.17414]
Trị riêng của ma trận A ban đầu:
[26.45002 -6.09195  4.8394  -0.3716   2.17414]
